import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import {
    QrCode,
    FileText,
    ArrowRight,
    ChevronRight,
    ShieldCheck,
    Check,
    Briefcase,
    GraduationCap,
    Compass,
    Building2,
    Clock,
    AlertCircle,
    CheckCircle2,
    Lock,
    Download,
    Users,
    Activity,
    Layers,
    Sliders,
    Sparkles,
    Terminal,
    ArrowUpRight,
    Zap,
    Globe,
    Cpu
} from 'lucide-react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Button from '../components/ui/Button';
import Badge from '../components/ui/Badge';
import ScrollLaptopMockup from '../components/landing/ScrollLaptopMockup';

const LandingPage = () => {
    const [openFaq, setOpenFaq] = useState(null);

    const toggleFaq = (index) => {
        setOpenFaq(openFaq === index ? null : index);
    };

    const stats = [
        { label: 'Active Placements', value: '14,800+', note: 'Enrolled across campuses', trend: '+28%' },
        { label: 'Verified Logbooks', value: '99.2%', note: 'Weekly reviews completed', trend: 'Audit-ready' },
        { label: 'Partner Institutions', value: '62+', note: 'Universities & colleges', trend: 'Multi-tenant' },
        { label: 'Host Employers', value: '1,200+', note: 'Active industry mentors', trend: 'Verified' }
    ];

    const lifecycleStages = [
        {
            step: '01',
            title: 'Placement Verification',
            desc: 'Host company registration, insurance clearance, and automated coordinator approval workflows.',
            icon: Building2
        },
        {
            step: '02',
            title: 'Daily Check-In & Rotating QR',
            desc: 'Proof-of-presence verification with rotating 30-second on-site QR cryptographic tokens.',
            icon: QrCode
        },
        {
            step: '03',
            title: 'Weekly Logbook Revisions',
            desc: 'Technical reflections drafted by students, reviewed with inline industry supervisor notes & approval locks.',
            icon: FileText
        },
        {
            step: '04',
            title: 'On-Site Faculty Visits',
            desc: 'Academic supervisors document physical field visits, student progress, rubric evaluations, and defense milestones.',
            icon: Compass
        },
        {
            step: '05',
            title: 'Standardized Rubrics',
            desc: 'Dual-perspective grading: Industry workplace competency assessment + University academic defense rubric.',
            icon: Sliders
        },
        {
            step: '06',
            title: 'Credit Board Sign-Off',
            desc: 'Instant sanitized audit dossier and automated completion readiness diagnostic verification.',
            icon: ShieldCheck
        }
    ];

    const faqs = [
        {
            q: "How does the rotating QR daily attendance verification work?",
            a: "Students check in using a rotating 30-second on-site QR token generated by the supervisor or via the secure student check-in terminal. The system calculates compliance against the institutional 75% threshold in real time."
        },
        {
            q: "How does the logbook revision workflow operate?",
            a: "When a student submits a weekly logbook, the assigned industry supervisor can either approve it or return it with specific revision guidance. The student revises and resubmits the entry. Once approved, the record is permanently locked."
        },
        {
            q: "How are faculty supervisors assigned and balanced?",
            a: "Attachment coordinators have a dedicated console showing all unassigned students, supervisor caseload saturation meters, and reassignment controls with an immutable history trail."
        },
        {
            q: "Can institutional data be exported for academic boards and audits?",
            a: "Yes. Coordinators and School Admins can generate sanitized, audit-ready CSV exports for placements, attendance logs, weekly logbooks, and graded assessments with a single click."
        },
        {
            q: "Is cross-institutional data isolated?",
            a: "Yes. The AMS architecture implements strict multi-tenant isolation, ensuring that each school's student dossiers, supervisor allocations, and audit logs remain strictly isolated."
        }
    ];

    return (
        <div className="min-h-screen bg-[#0d0e12] font-sans text-slate-100 selection:bg-violet-500/30 overflow-x-hidden">
            <Navbar />

            {/* ========================================================================= */}
            {/* 1. STRIPE-INSPIRED HERO SECTION WITH ANGLED GLOWING MESH BACKDROP */}
            {/* ========================================================================= */}
            <section className="relative pt-28 sm:pt-36 pb-12 overflow-hidden">
                {/* Stripe-style angled multi-color mesh gradient backdrop */}
                <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-7xl h-[700px] pointer-events-none -z-10 overflow-hidden">
                    {/* Glowing Mesh Orbs */}
                    <div className="absolute -top-32 -left-20 w-[600px] h-[500px] bg-gradient-to-br from-violet-600/30 via-indigo-600/20 to-transparent blur-[140px] rounded-full transform -rotate-12" />
                    <div className="absolute top-10 right-0 w-[550px] h-[450px] bg-gradient-to-bl from-cyan-500/25 via-teal-500/15 to-transparent blur-[130px] rounded-full" />
                    <div className="absolute top-48 left-1/3 w-[500px] h-[350px] bg-gradient-to-tr from-fuchsia-600/20 via-rose-500/10 to-transparent blur-[120px] rounded-full" />

                    {/* Subtle Angled Perspective Grid Lines */}
                    <div className="absolute inset-0 bg-[linear-gradient(to_right,#1f2333_1px,transparent_1px),linear-gradient(to_bottom,#1f2333_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] opacity-30" />
                </div>

                <div className="max-w-6xl mx-auto px-4 sm:px-6 text-center relative z-10">
                    {/* Raycast / Linear Command Pill */}
                    <div className="inline-flex items-center gap-2.5 px-3.5 py-1.5 rounded-full bg-[#151722]/90 border border-[#2b2e42] text-xs text-slate-300 mb-6 shadow-xl backdrop-blur-md hover:border-violet-500/40 transition-colors cursor-default">
                        <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                        <span className="font-semibold text-white tracking-tight">Institutional Attachment Infrastructure</span>
                        <span className="text-slate-600 font-mono">•</span>
                        <span className="px-1.5 py-0.5 rounded bg-[#202336] text-[10px] font-mono text-violet-300 border border-[#343852]">
                            v2.4 Active
                        </span>
                    </div>

                    {/* Main Stripe-style Headline */}
                    <h1 className="text-4xl sm:text-6xl md:text-7xl font-extrabold text-white tracking-tight leading-[1.08] max-w-4xl mx-auto">
                        The Modern Operating System for{' '}
                        <span className="text-transparent bg-clip-text bg-gradient-to-r from-violet-400 via-cyan-300 to-indigo-300">
                            University Attachments.
                        </span>
                    </h1>

                    {/* Subtitle */}
                    <p className="mt-5 text-sm sm:text-base md:text-lg text-slate-300 max-w-2xl mx-auto leading-relaxed font-normal">
                        A unified, policy-compliant workspace connecting student attachees, workplace industry mentors, faculty supervisors, and university coordinators under verifiable academic governance.
                    </p>

                    {/* Dual Action CTAs */}
                    <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-3.5">
                        <Link to="/login">
                            <Button size="lg" className="w-full sm:w-auto px-7 py-3.5 bg-violet-600 hover:bg-violet-500 text-white font-bold rounded-xl shadow-lg shadow-violet-600/30 flex items-center gap-2 text-sm">
                                <span>Sign In to Portal</span>
                                <ArrowRight size={16} />
                            </Button>
                        </Link>
                        <Link to="/signup">
                            <Button variant="outline" size="lg" className="w-full sm:w-auto px-6 py-3.5 border-[#2c3042] bg-[#12141c]/80 hover:bg-[#181a24] text-slate-200 hover:text-white font-semibold rounded-xl text-sm flex items-center gap-2">
                                <Building2 size={16} className="text-violet-400" />
                                <span>Register Institution</span>
                            </Button>
                        </Link>
                    </div>

                    {/* Live Telemetry Status Strip */}
                    <div className="mt-10 inline-flex flex-wrap items-center justify-center gap-4 sm:gap-6 px-4 py-2 rounded-xl bg-[#12141c]/80 border border-[#22242f] text-xs text-slate-400 font-mono">
                        <div className="flex items-center gap-2">
                            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                            <span>99.98% Uptime SLA</span>
                        </div>
                        <span className="text-slate-700 hidden sm:inline">•</span>
                        <div className="flex items-center gap-1.5">
                            <Lock size={12} className="text-violet-400" />
                            <span>Multi-Tenant Isolated</span>
                        </div>
                        <span className="text-slate-700 hidden sm:inline">•</span>
                        <div className="flex items-center gap-1.5">
                            <ShieldCheck size={13} className="text-cyan-400" />
                            <span>Verifiable Audit Ledger</span>
                        </div>
                    </div>
                </div>
            </section>

            {/* ========================================================================= */}
            {/* 2. SCROLL-DRIVEN 3D LAPTOP SCREEN ENTRY ANIMATION                         */}
            {/* ========================================================================= */}
            <section id="workspaces" className="relative w-full py-6">
                <ScrollLaptopMockup />
            </section>

            {/* ========================================================================= */}
            {/* 3. METRIC BENCHMARKS & STATS STRIP */}
            {/* ========================================================================= */}
            <section className="relative max-w-6xl mx-auto px-4 sm:px-6 py-12">
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                    {stats.map((stat, idx) => (
                        <div key={idx} className="bg-[#12141c] border border-[#22242f] rounded-2xl p-5 hover:border-[#2f3244] transition-all duration-200 group">
                            <div className="flex items-center justify-between">
                                <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">{stat.label}</span>
                                <span className="text-[10px] font-mono font-bold text-violet-400 bg-violet-500/10 px-2 py-0.5 rounded border border-violet-500/20">
                                    {stat.trend}
                                </span>
                            </div>
                            <span className="text-3xl font-bold text-white font-mono block mt-2 group-hover:text-violet-300 transition-colors">
                                {stat.value}
                            </span>
                            <span className="text-xs text-slate-500 block mt-1">{stat.note}</span>
                        </div>
                    ))}
                </div>
            </section>

            {/* ========================================================================= */}
            {/* 4. 6-STAGE ATTACHMENT LIFECYCLE */}
            {/* ========================================================================= */}
            <section id="features" className="relative max-w-6xl mx-auto px-4 sm:px-6 py-16">
                <div className="text-center max-w-3xl mx-auto mb-12">
                    <span className="text-[10px] font-bold uppercase tracking-wider text-violet-400 bg-violet-500/10 px-2.5 py-1 rounded-md border border-violet-500/20">
                        End-to-End Governance
                    </span>
                    <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight mt-3">
                        The 6-Stage Industrial Attachment Lifecycle
                    </h2>
                    <p className="text-sm text-slate-400 mt-2">
                        Verifiable milestones structured for university degree compliance, credit boards, and employer partnerships.
                    </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {lifecycleStages.map((stage, idx) => {
                        const Icon = stage.icon;
                        return (
                            <div
                                key={idx}
                                className="bg-[#12141c] border border-[#22242f] hover:border-[#2f3244] rounded-2xl p-6 transition-all duration-300 space-y-4 hover:shadow-xl hover:shadow-black/40 group relative overflow-hidden"
                            >
                                <div className="flex items-center justify-between">
                                    <div className="w-12 h-12 rounded-xl bg-violet-600/10 border border-violet-500/20 text-violet-400 flex items-center justify-center group-hover:bg-violet-600 group-hover:text-white transition-all duration-300">
                                        <Icon size={22} />
                                    </div>
                                    <span className="text-xs font-mono font-bold text-slate-500 bg-[#181a24] px-2.5 py-1 rounded-lg border border-[#22242f]">
                                        STAGE {stage.step}
                                    </span>
                                </div>
                                <div>
                                    <h3 className="text-base font-bold text-white group-hover:text-violet-300 transition-colors">
                                        {stage.title}
                                    </h3>
                                    <p className="text-xs text-slate-400 mt-1.5 leading-relaxed">
                                        {stage.desc}
                                    </p>
                                </div>
                            </div>
                        );
                    })}
                </div>
            </section>

            {/* ========================================================================= */}
            {/* 5. FREQUENTLY ASKED QUESTIONS */}
            {/* ========================================================================= */}
            <section className="relative max-w-4xl mx-auto px-4 sm:px-6 py-16">
                <div className="text-center mb-10">
                    <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Frequently Asked Questions</h2>
                    <p className="text-xs sm:text-sm text-slate-400 mt-1">Key institutional questions regarding deployment and compliance.</p>
                </div>

                <div className="space-y-3">
                    {faqs.map((faq, idx) => (
                        <div key={idx} className="rounded-xl bg-[#12141c] border border-[#22242f] overflow-hidden transition-all">
                            <button
                                onClick={() => toggleFaq(idx)}
                                className="w-full p-4 text-left flex items-center justify-between text-xs sm:text-sm font-semibold text-slate-200 hover:text-white transition-colors cursor-pointer"
                            >
                                <span>{faq.q}</span>
                                <ChevronRight
                                    size={16}
                                    className={`text-slate-500 transition-transform duration-200 ${
                                        openFaq === idx ? 'rotate-90 text-violet-400' : ''
                                    }`}
                                />
                            </button>
                            {openFaq === idx && (
                                <div className="px-4 pb-4 text-xs text-slate-400 leading-relaxed border-t border-[#1e2230] pt-3">
                                    {faq.a}
                                </div>
                            )}
                        </div>
                    ))}
                </div>
            </section>

            {/* ========================================================================= */}
            {/* 6. FINAL CTA BANNER */}
            {/* ========================================================================= */}
            <section className="relative max-w-6xl mx-auto px-4 sm:px-6 py-16">
                <div className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-violet-900/40 via-indigo-900/30 to-slate-900/50 border border-violet-500/30 p-8 sm:p-12 text-center shadow-2xl">
                    <div className="absolute top-0 right-0 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl pointer-events-none" />

                    <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
                        Transform Industrial Attachment Governance Today.
                    </h2>
                    <p className="text-xs sm:text-sm text-slate-300 max-w-xl mx-auto mt-3 leading-relaxed">
                        Deploy AttachPro for your university faculty or company mentorship network in minutes.
                    </p>

                    <div className="mt-6 flex flex-col sm:flex-row items-center justify-center gap-3">
                        <Link to="/signup">
                            <Button size="lg" className="w-full sm:w-auto px-8 py-3 bg-white text-slate-950 hover:bg-slate-100 font-bold rounded-xl text-xs uppercase tracking-wider">
                                Register Your Campus
                            </Button>
                        </Link>
                        <Link to="/login">
                            <Button variant="outline" size="lg" className="w-full sm:w-auto px-6 py-3 border-[#3d4257] text-white hover:bg-white/10 font-semibold rounded-xl text-xs">
                                Access Existing Account
                            </Button>
                        </Link>
                    </div>
                </div>
            </section>

            <Footer />
        </div>
    );
};

export default LandingPage;
