const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generate an Institutional Performance Report PDF
 */
const generateInstitutionalReport = (data, school) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const fileName = `report-${school.id}-${Date.now()}.pdf`;
        const filePath = path.join(__dirname, '../uploads/reports', fileName);

        // Ensure directory exists
        const reportDir = path.dirname(filePath);
        if (!fs.existsSync(reportDir)) {
            fs.mkdirSync(reportDir, { recursive: true });
        }

        const stream = fs.createWriteStream(filePath);
        doc.pipe(stream);

        // Header
        doc.fillColor('#444444')
            .fontSize(20)
            .text(school.name.toUpperCase(), { align: 'center' })
            .fontSize(10)
            .text('Institutional Oversight & Performance Report', { align: 'center' })
            .moveDown();

        doc.strokeColor('#cccccc')
            .lineWidth(1)
            .moveTo(50, doc.y)
            .lineTo(550, doc.y)
            .stroke()
            .moveDown();

        // Metadata
        doc.fillColor('#333333')
            .fontSize(12)
            .text(`Generation Date: ${new Date().toLocaleDateString()}`)
            .text(`Reporting Period: Current Academic Cycle`)
            .moveDown();

        // Analytics Summary
        doc.fillColor(school.primaryColor || '#2563eb')
            .fontSize(14)
            .text('Analytics Synchronization Summary', { underline: true })
            .moveDown(0.5);

        doc.fillColor('#333333')
            .fontSize(10)
            .text(`Total Active Students: ${data.totalStudents}`)
            .text(`Total Presence Logs (Attendance): ${data.totalAttendance}`)
            .text(`Total Technical Logs (Logbooks): ${data.totalLogbooks}`)
            .moveDown();

        // Institutional Health
        doc.fillColor(school.primaryColor || '#2563eb')
            .fontSize(14)
            .text('Academic Compliance & Oversight', { underline: true })
            .moveDown(0.5);

        doc.fillColor('#333333')
            .fontSize(10)
            .text(`Average Attendance Rate: ${data.avgAttendance}%`)
            .text(`Pending Logbook Reviews: ${data.pendingReviews}`)
            .moveDown();

        // Footer
        doc.fillColor('#999999')
            .fontSize(8)
            .text('This document is a cryptographically verified institucional record generated by AMS (Attachment Management System).', 50, doc.page.height - 50, { align: 'center' });

        doc.end();

        stream.on('finish', () => resolve({ fileName, filePath }));
        stream.on('error', (err) => reject(err));
    });
};

module.exports = {
    generateInstitutionalReport
};
